services:
  - type: web
    name: minutoeuf
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: minutoeuf
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
    buildCommand: docker build -t minutoeuf .
    startCommand: docker run -p $PORT:80 -e MONGODB_URI=$MONGODB_URI minutoeuf
    healthCheckPath: /
    autoDeploy: true
    plan: free
