services:
  - type: web
    name: minutoeuf
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://wadyx38:k7NYq73UdTaU9vwH@cluster0.4xafp.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0&tls=true&authSource=admin&ssl=true
      - key: MONGODB_DATABASE
        value: minutoeuf
    buildCommand: docker build -t minutoeuf .
    startCommand: docker run -p $PORT:80 minutoeuf
    healthCheckPath: /
    autoDeploy: true
